# <font color='#FFE15D'>**Week 3: Multiple Linear Regression 📈**</font>

## **🔸 Imports**

In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# import sklearn
# from sklearn import linear_model
from sklearn.linear_model import LinearRegression, SGDRegressor

## **🔸 Data**

### Load data

In [ ]:
df = pd.read_csv('data/usa-housing-train-preprocessed.csv')
df

### Split x & y

In [ ]:
train_set = np.array(df)[:, 1:]
x_train = train_set[:, 0:5]
y_train = train_set[:, 5]
x_train.shape, y_train.shape

### Visualize

In [ ]:
plt.scatter(x_train[:, 4], y_train)

## **🔸 Model**

In [ ]:
n, m = x_train.shape

x = x_train[0, :]
x_aug = np.hstack((1, x))
print(x_aug)

w = np.random.randn(6)
print(w)

y_hat = 0
for xi, wi in zip(x, w):
    y_hat += xi*wi
y_hat

In [ ]:
n, m = x_train.shape

x = np.hstack((np.ones((n, 1)), x_train))

w = np.random.randn(m+1)

y_hat = 0
for xi, wi in zip(x_train_aug.T, w):
    y_hat += xi*wi
y_hat.shape

### Define model

In [ ]:
def multiple_linear_regression(x, w):
    y_hat = 0
    for xi, wi in zip(x.T, w):
        y_hat += xi*wi
    return y_hat

### Pass data to the model

#### - Initialize weight and bias

In [ ]:
w = np.random.randn(m+1)
w.shape

#### - Get model's output

In [ ]:
x_train_aug = np.hstack((np.ones((n, 1)), x_train))
y_hat = multiple_linear_regression(x_train_aug, w)
y_hat.shape

## **🔸 Train**

### Functions

In [ ]:
def multiple_linear_regression(x, w):
    y_hat = 0
    for xi, wi in zip(x.T, w):
        y_hat += xi*wi
    return y_hat

In [ ]:
def mse(y, y_hat):
    loss = np.mean((y - y_hat)**2)
    return loss

In [ ]:
def gradient(x, y, y_hat):
    grads = []
    for xi in x.T:
        grads.append(2*np.mean(xi * (y_hat - y)))
    grads = np.array(grads)
    return grads

In [ ]:
def gradient_descent(w, eta, grads):
    w -= eta*grads
    return w

### Load Train Dataset

In [ ]:
df = pd.read_csv('data/usa-housing-train-preprocessed.csv')
train_set = np.array(df)[:, 1:]

x_train = train_set[:, 0:5]
y_train = train_set[:, 5]

n, m = x_train.shape
x_train = np.hstack((np.ones((n, 1)), x_train))
x_train.shape

### Initialization

In [ ]:
w = np.random.randn(m+1)

eta = 0.5
n_epochs = 2000

### Main

In [ ]:
error_hist = []

for epoch in range(n_epochs):
    # predictions
    y_hat = multiple_linear_regression(x_train, w)

    # loss
    e = mse(y_train, y_hat)
    error_hist.append(e)
    
    # gradients
    grads = gradient(x_train, y_train, y_hat)
    
    # gradient descent
    w = gradient_descent(w, eta, grads)
    
    if (epoch+1) % 100 == 0:
        print(f'Epoch={epoch}, \t E={e:.4},\t w={w}')

### Learning curve

In [ ]:
plt.plot(error_hist)

### Save model

In [ ]:
np.save('multiple-linear-regression-weights', w)

## **🔸 Test**

### Functions

In [ ]:
def multiple_linear_regression(x, w):
    y_hat = 0
    for xi, wi in zip(x.T, w):
        y_hat += xi*wi
    return y_hat

In [ ]:
def mae(y, y_hat):
    loss = np.mean(np.abs(y - y_hat))
    return loss

In [ ]:
def r2(y, y_hat):
    return 1 - np.sum((y - y_hat)**2) / np.sum((y - y.mean())**2)

### Load Test Dataset

In [ ]:
df = pd.read_csv('data/usa-housing-test-preprocessed.csv')
test_set = np.array(df)[:, 1:]

x_test = test_set[:, 0:5]
y_test = test_set[:, 5]

n, m = x_test.shape
x_test = np.hstack((np.ones((n, 1)), x_test))
x_test.shape

### Load Trained Model

In [ ]:
w = np.load('multiple-linear-regression-weights.npy')
w

### Evaluate

In [ ]:
y_hat_test = multiple_linear_regression(x_test, w)

In [ ]:
mae(y_test, y_hat_test)

In [ ]:
r2(y_test, y_hat_test)

## **🔸 Vectorization**

### Functions

In [ ]:
def multiple_linear_regression(x, w):
    y_hat = x @ w
    return y_hat

In [ ]:
def mse(y, y_hat):
    loss = np.mean((y - y_hat)**2)
    return loss #, np.linalg.norm(y-y_hat)**2 / len(y), ((y_hat - y).T @ (y_hat - y)) / len(y)

In [ ]:
def gradient(x, y, y_hat):
    grads = 2*(x.T @ (y_hat - y)) / x.shape[0]
    return grads

In [ ]:
def gradient_descent(w, eta, grads):
    w -= eta*grads
    return w

In [ ]:
def mae(y, y_hat):
    loss = np.mean(np.abs(y - y_hat))
    return loss

In [ ]:
def r2(y, y_hat):
    return 1 - np.sum((y - y_hat)**2) / np.sum((y - y.mean())**2)

### Train

#### - Load Dataset

In [ ]:
df = pd.read_csv('data/usa-housing-train-preprocessed.csv')
train_set = np.array(df)[:, 1:]

x_train = train_set[:, 0:5]
y_train = train_set[:, [5]]

n, m = x_train.shape
x_train = np.hstack((np.ones((n, 1)), x_train))
x_train.shape, y_train.shape

#### - Initialization

In [ ]:
w = np.random.randn(m+1, 1)
print(w.shape)

eta = 0.01
n_epochs = 2000

#### - Main

In [ ]:
error_hist = []

for epoch in range(n_epochs):
    # predictions
    y_hat = multiple_linear_regression(x_train, w)

    # loss
    e = mse(y_train, y_hat)
    error_hist.append(e)
    
    # gradients
    grads = gradient(x_train, y_train, y_hat)
    
    # gradient descent
    w = gradient_descent(w, eta, grads)
    
    if (epoch+1) % 100 == 0:
        print(f'Epoch={epoch}, \t E={e:.4},\t w={w.T[0]}')

### Learning curve

In [ ]:
plt.plot(error_hist)

### Save model

In [ ]:
np.save('multiple-linear-regression-weights-vec', w)

### Test

In [ ]:
df = pd.read_csv('data/usa-housing-test-preprocessed.csv')
test_set = np.array(df)[:, 1:]

x_test = test_set[:, 0:5]
y_test = test_set[:, [5]]

n, m = x_test.shape
x_test = np.hstack((np.ones((n, 1)), x_test))
x_test.shape, y_test.shape

In [ ]:
y_hat_test = multiple_linear_regression(x_test, w)
y_hat_test.shape

In [ ]:
mae(y_test, y_hat_test)

In [ ]:
r2(y_test, y_hat_test)

## **🔸 Closed-form Solution**

$
\begin{align}
w &= (X^TX)^{-1} X^T y
\end{align}
$

In [ ]:
df = pd.read_csv('data/usa-housing-train-preprocessed.csv')
train_set = np.array(df)[:, 1:]

x_train = train_set[:, 0:5]
y_train = train_set[:, [5]]

n, m = x_train.shape
x_train = np.hstack((np.ones((n, 1)), x_train))
x_train.shape, y_train.shape

In [ ]:
X = x_train.copy()
y = y_train.copy()
X.shape, y.shape

In [ ]:
wc = np.linalg.inv(X.T @ X) @ X.T @ y
wc

In [ ]:
w

### Test

In [ ]:
df = pd.read_csv('data/usa-housing-test-preprocessed.csv')
test_set = np.array(df)[:, 1:]

x_test = test_set[:, 0:5]
y_test = test_set[:, [5]]

n, m = x_test.shape
x_test = np.hstack((np.ones((n, 1)), x_test))
x_test.shape, y_test.shape

In [ ]:
y_hat_test = multiple_linear_regression(x_test, wc)
y_hat_test.shape

In [ ]:
mae(y_test, y_hat_test)

In [ ]:
r2(y_test, y_hat_test)

## **🔸 scikit-learn: LinearRegression()**

### Train Dataset

In [ ]:
df = pd.read_csv('data/usa-housing-train-preprocessed.csv')
train_set = np.array(df)[:, 1:]

x_train = train_set[:, 0:5]
y_train = train_set[:, [5]]

n, m = x_train.shape
x_train = np.hstack((np.ones((n, 1)), x_train))
x_train.shape, y_train.shape

### Test Dataset

In [ ]:
df = pd.read_csv('data/usa-housing-test-preprocessed.csv')
test_set = np.array(df)[:, 1:]

x_test = test_set[:, 0:5]
y_test = test_set[:, [5]]

n, m = x_test.shape
x_test = np.hstack((np.ones((n, 1)), x_test))
x_test.shape, y_test.shape

### Model

In [ ]:
model = LinearRegression()
model

In [ ]:
model.coef_, model.rank_

### Train

In [ ]:
model.fit(x_train, y_train)

In [ ]:
model.intercept_, model.coef_, model.rank_

### Test

In [ ]:
model.score(x_train, y_train)

In [ ]:
model.score(x_test, y_test)

In [ ]:
y_hat = model.predict(x_test[[0], :])
y_hat

## **🔸 scikit-learn: SGDRegressor()**

### Train Dataset

In [62]:
df = pd.read_csv('data/usa-housing-train-preprocessed.csv')
train_set = np.array(df)[:, 1:]

x_train = train_set[:, 0:5]
y_train = train_set[:, 5]

n, m = x_train.shape
x_train = np.hstack((np.ones((n, 1)), x_train))
x_train.shape, y_train.shape

((3500, 6), (3500,))

### Test Dataset

In [63]:
df = pd.read_csv('data/usa-housing-test-preprocessed.csv')
test_set = np.array(df)[:, 1:]

x_test = test_set[:, 0:5]
y_test = test_set[:, 5]

n, m = x_test.shape
x_test = np.hstack((np.ones((n, 1)), x_test))
x_test.shape, y_test.shape

((1500, 6), (1500,))

### Model

In [72]:
model = SGDRegressor(verbose=1, eta0=0.1, tol=1e-5)
model

SGDRegressor(eta0=0.1, tol=1e-05, verbose=1)

### Train

In [73]:
model.fit(x_train, y_train)

-- Epoch 1
Norm: 0.70, NNZs: 6, Bias: 0.611010, T: 3500, Avg. loss: 0.006862
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 0.70, NNZs: 6, Bias: 0.618085, T: 7000, Avg. loss: 0.005384
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 0.71, NNZs: 6, Bias: 0.623544, T: 10500, Avg. loss: 0.005354
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 0.70, NNZs: 6, Bias: 0.626133, T: 14000, Avg. loss: 0.005323
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 0.70, NNZs: 6, Bias: 0.619789, T: 17500, Avg. loss: 0.005344
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 0.69, NNZs: 6, Bias: 0.614896, T: 21000, Avg. loss: 0.005306
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 0.70, NNZs: 6, Bias: 0.619089, T: 24500, Avg. loss: 0.005317
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 0.70, NNZs: 6, Bias: 0.619285, T: 28000, Avg. loss: 0.005278
Total training time: 0.00 seconds.
-- Epoch 9
Norm: 0.70, NNZs: 6, Bias: 0.632882, T: 31500, Avg. loss: 0.005282
Total training time:

SGDRegressor(eta0=0.1, tol=1e-05, verbose=1)

In [74]:
model.intercept_, model.coef_

(array([0.61600256]),
 array([0.59073921, 0.22552151, 0.16749133, 0.12858162, 0.01144052,
        0.15260798]))

### Test

In [75]:
model.score(x_train, y_train)

0.9126978957275029

In [76]:
model.score(x_test, y_test)

0.9065903730536611

In [77]:
y_hat = model.predict(x_test[[0], :])
y_hat

array([1.28237512])